language: python
addons:
  firefox: "38.0.5"
python:
  - "2.7"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - ./bootstrap.py
script:
  - make
  - make behave
notifications:
  slack: ccnmtl:GizSNscLWJLldjQrffB8mwgm
