# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20150617_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageuploaditem',
            name='doc',
            field=models.FileField(
                max_length=255,
                upload_to=b'documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='libraryitem',
            name='doc',
            field=models.FileField(
                max_length=255,
                upload_to=b'documents/%Y/%m/%d'),
        ),
    ]
