# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20160615_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.CharField(
                choices=[
                    (b'a', b'archived'),
                    (b'd', b'in development'),
                    (b'p', b'published')],
                default=b'd',
                max_length=1),
        ),
    ]
