# flake8: noqa
# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-30 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_case_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cohort',
            options={'ordering': ['name']},
        ),
    ]
