# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-19 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gate_block', '0012_auto_20161130_1605'),
        ('pagetree', '0002_delete_testblock'),
        ('main', '0046_auto_20161209_1642'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UELCHandler',
        ),
    ]
